// lib/core/errors/failures.dart

import 'package:freezed_annotation/freezed_annotation.dart';

part 'failures.freezed.dart'; // This file will be generated by build_runner

@freezed
class Failure with _$Failure {
  /// Represents an error from the server (e.g., HTTP 500, invalid data).
  const factory Failure.serverFailure(String message) = ServerFailure;

  /// Represents a network-related error (e.g., no internet connection).
  const factory Failure.networkFailure() = NetworkFailure;

  /// Represents an error related to caching or local storage.
  const factory Failure.cacheFailure() = CacheFailure;

  /// Represents an authentication-specific error (e.g., invalid credentials, token expired).
  const factory Failure.authFailure(String message) = AuthFailure;

  /// Represents an unknown error that doesn't fit any of the above categories.
  const factory Failure.unknownFailure(String message) = UnknownFailure;

// Add any other specific failure types you might need, e.g.:
// const factory Failure.validationFailure(List<String> errors) = ValidationFailure;
// const factory Failure.notFoundFailure() = NotFoundFailure;
}